version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local

# services:
#   mongo:
#     image: mongo
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#     ports:
#       - "27017:27017"
#     volumes:
#       - ./mongo-data:/data/db

#   nestjs-app:
#     build: .
#     ports:
#       - "4444:4444"
#     environment:
#       - NODE_ENV=production
#       - MONGO_URI=mongodb://root:example@localhost:27017/docs?authSource=admin
#     depends_on:
#       - mongo
#     volumes:
#       - .:/usr/src/app
    # command: yarn start:prod